// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.2
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

// AXILiteS
// 0x00 : reserved
// 0x04 : reserved
// 0x08 : reserved
// 0x0c : reserved
// 0x10 : Data signal of bias
//        bit 31~0 - bias[31:0] (Read)
// 0x14 : Control signal of bias
//        bit 0  - bias_ap_vld (Read/COR)
//        others - reserved
// 0x18 : Data signal of w1
//        bit 31~0 - w1[31:0] (Read)
// 0x1c : Control signal of w1
//        bit 0  - w1_ap_vld (Read/COR)
//        others - reserved
// 0x20 : Data signal of w2
//        bit 31~0 - w2[31:0] (Read)
// 0x24 : Control signal of w2
//        bit 0  - w2_ap_vld (Read/COR)
//        others - reserved
// 0x28 : Data signal of w3
//        bit 31~0 - w3[31:0] (Read)
// 0x2c : Control signal of w3
//        bit 0  - w3_ap_vld (Read/COR)
//        others - reserved
// 0x30 : Data signal of w4
//        bit 31~0 - w4[31:0] (Read)
// 0x34 : Control signal of w4
//        bit 0  - w4_ap_vld (Read/COR)
//        others - reserved
// 0x38 : Data signal of w5
//        bit 31~0 - w5[31:0] (Read)
// 0x3c : Control signal of w5
//        bit 0  - w5_ap_vld (Read/COR)
//        others - reserved
// (SC = Self Clear, COR = Clear on Read, TOW = Toggle on Write, COH = Clear on Handshake)

#define XBACKWARD_LITE_AXILITES_ADDR_BIAS_DATA 0x10
#define XBACKWARD_LITE_AXILITES_BITS_BIAS_DATA 32
#define XBACKWARD_LITE_AXILITES_ADDR_BIAS_CTRL 0x14
#define XBACKWARD_LITE_AXILITES_ADDR_W1_DATA   0x18
#define XBACKWARD_LITE_AXILITES_BITS_W1_DATA   32
#define XBACKWARD_LITE_AXILITES_ADDR_W1_CTRL   0x1c
#define XBACKWARD_LITE_AXILITES_ADDR_W2_DATA   0x20
#define XBACKWARD_LITE_AXILITES_BITS_W2_DATA   32
#define XBACKWARD_LITE_AXILITES_ADDR_W2_CTRL   0x24
#define XBACKWARD_LITE_AXILITES_ADDR_W3_DATA   0x28
#define XBACKWARD_LITE_AXILITES_BITS_W3_DATA   32
#define XBACKWARD_LITE_AXILITES_ADDR_W3_CTRL   0x2c
#define XBACKWARD_LITE_AXILITES_ADDR_W4_DATA   0x30
#define XBACKWARD_LITE_AXILITES_BITS_W4_DATA   32
#define XBACKWARD_LITE_AXILITES_ADDR_W4_CTRL   0x34
#define XBACKWARD_LITE_AXILITES_ADDR_W5_DATA   0x38
#define XBACKWARD_LITE_AXILITES_BITS_W5_DATA   32
#define XBACKWARD_LITE_AXILITES_ADDR_W5_CTRL   0x3c

