// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.2
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

`timescale 1ns/1ps
module backward_lite_AXILiteS_s_axi
#(parameter
    C_S_AXI_ADDR_WIDTH = 6,
    C_S_AXI_DATA_WIDTH = 32
)(
    // axi4 lite slave signals
    input  wire                          ACLK,
    input  wire                          ARESET,
    input  wire                          ACLK_EN,
    input  wire [C_S_AXI_ADDR_WIDTH-1:0] AWADDR,
    input  wire                          AWVALID,
    output wire                          AWREADY,
    input  wire [C_S_AXI_DATA_WIDTH-1:0] WDATA,
    input  wire [C_S_AXI_DATA_WIDTH/8-1:0] WSTRB,
    input  wire                          WVALID,
    output wire                          WREADY,
    output wire [1:0]                    BRESP,
    output wire                          BVALID,
    input  wire                          BREADY,
    input  wire [C_S_AXI_ADDR_WIDTH-1:0] ARADDR,
    input  wire                          ARVALID,
    output wire                          ARREADY,
    output wire [C_S_AXI_DATA_WIDTH-1:0] RDATA,
    output wire [1:0]                    RRESP,
    output wire                          RVALID,
    input  wire                          RREADY,
    // user signals
    input  wire [31:0]                   bias,
    input  wire                          bias_ap_vld,
    input  wire [31:0]                   w1,
    input  wire                          w1_ap_vld,
    input  wire [31:0]                   w2,
    input  wire                          w2_ap_vld,
    input  wire [31:0]                   w3,
    input  wire                          w3_ap_vld,
    input  wire [31:0]                   w4,
    input  wire                          w4_ap_vld,
    input  wire [31:0]                   w5,
    input  wire                          w5_ap_vld
);
//------------------------Address Info-------------------
// 0x00 : reserved
// 0x04 : reserved
// 0x08 : reserved
// 0x0c : reserved
// 0x10 : Data signal of bias
//        bit 31~0 - bias[31:0] (Read)
// 0x14 : Control signal of bias
//        bit 0  - bias_ap_vld (Read/COR)
//        others - reserved
// 0x18 : Data signal of w1
//        bit 31~0 - w1[31:0] (Read)
// 0x1c : Control signal of w1
//        bit 0  - w1_ap_vld (Read/COR)
//        others - reserved
// 0x20 : Data signal of w2
//        bit 31~0 - w2[31:0] (Read)
// 0x24 : Control signal of w2
//        bit 0  - w2_ap_vld (Read/COR)
//        others - reserved
// 0x28 : Data signal of w3
//        bit 31~0 - w3[31:0] (Read)
// 0x2c : Control signal of w3
//        bit 0  - w3_ap_vld (Read/COR)
//        others - reserved
// 0x30 : Data signal of w4
//        bit 31~0 - w4[31:0] (Read)
// 0x34 : Control signal of w4
//        bit 0  - w4_ap_vld (Read/COR)
//        others - reserved
// 0x38 : Data signal of w5
//        bit 31~0 - w5[31:0] (Read)
// 0x3c : Control signal of w5
//        bit 0  - w5_ap_vld (Read/COR)
//        others - reserved
// (SC = Self Clear, COR = Clear on Read, TOW = Toggle on Write, COH = Clear on Handshake)

//------------------------Parameter----------------------
localparam
    ADDR_BIAS_DATA_0 = 6'h10,
    ADDR_BIAS_CTRL   = 6'h14,
    ADDR_W1_DATA_0   = 6'h18,
    ADDR_W1_CTRL     = 6'h1c,
    ADDR_W2_DATA_0   = 6'h20,
    ADDR_W2_CTRL     = 6'h24,
    ADDR_W3_DATA_0   = 6'h28,
    ADDR_W3_CTRL     = 6'h2c,
    ADDR_W4_DATA_0   = 6'h30,
    ADDR_W4_CTRL     = 6'h34,
    ADDR_W5_DATA_0   = 6'h38,
    ADDR_W5_CTRL     = 6'h3c,
    WRIDLE           = 2'd0,
    WRDATA           = 2'd1,
    WRRESP           = 2'd2,
    WRRESET          = 2'd3,
    RDIDLE           = 2'd0,
    RDDATA           = 2'd1,
    RDRESET          = 2'd2,
    ADDR_BITS         = 6;

//------------------------Local signal-------------------
    reg  [1:0]                    wstate = WRRESET;
    reg  [1:0]                    wnext;
    reg  [ADDR_BITS-1:0]          waddr;
    wire [31:0]                   wmask;
    wire                          aw_hs;
    wire                          w_hs;
    reg  [1:0]                    rstate = RDRESET;
    reg  [1:0]                    rnext;
    reg  [31:0]                   rdata;
    wire                          ar_hs;
    wire [ADDR_BITS-1:0]          raddr;
    // internal registers
    reg  [31:0]                   int_bias = 'b0;
    reg                           int_bias_ap_vld;
    reg  [31:0]                   int_w1 = 'b0;
    reg                           int_w1_ap_vld;
    reg  [31:0]                   int_w2 = 'b0;
    reg                           int_w2_ap_vld;
    reg  [31:0]                   int_w3 = 'b0;
    reg                           int_w3_ap_vld;
    reg  [31:0]                   int_w4 = 'b0;
    reg                           int_w4_ap_vld;
    reg  [31:0]                   int_w5 = 'b0;
    reg                           int_w5_ap_vld;

//------------------------Instantiation------------------

//------------------------AXI write fsm------------------
assign AWREADY = (wstate == WRIDLE);
assign WREADY  = (wstate == WRDATA);
assign BRESP   = 2'b00;  // OKAY
assign BVALID  = (wstate == WRRESP);
assign wmask   = { {8{WSTRB[3]}}, {8{WSTRB[2]}}, {8{WSTRB[1]}}, {8{WSTRB[0]}} };
assign aw_hs   = AWVALID & AWREADY;
assign w_hs    = WVALID & WREADY;

// wstate
always @(posedge ACLK) begin
    if (ARESET)
        wstate <= WRRESET;
    else if (ACLK_EN)
        wstate <= wnext;
end

// wnext
always @(*) begin
    case (wstate)
        WRIDLE:
            if (AWVALID)
                wnext = WRDATA;
            else
                wnext = WRIDLE;
        WRDATA:
            if (WVALID)
                wnext = WRRESP;
            else
                wnext = WRDATA;
        WRRESP:
            if (BREADY)
                wnext = WRIDLE;
            else
                wnext = WRRESP;
        default:
            wnext = WRIDLE;
    endcase
end

// waddr
always @(posedge ACLK) begin
    if (ACLK_EN) begin
        if (aw_hs)
            waddr <= AWADDR[ADDR_BITS-1:0];
    end
end

//------------------------AXI read fsm-------------------
assign ARREADY = (rstate == RDIDLE);
assign RDATA   = rdata;
assign RRESP   = 2'b00;  // OKAY
assign RVALID  = (rstate == RDDATA);
assign ar_hs   = ARVALID & ARREADY;
assign raddr   = ARADDR[ADDR_BITS-1:0];

// rstate
always @(posedge ACLK) begin
    if (ARESET)
        rstate <= RDRESET;
    else if (ACLK_EN)
        rstate <= rnext;
end

// rnext
always @(*) begin
    case (rstate)
        RDIDLE:
            if (ARVALID)
                rnext = RDDATA;
            else
                rnext = RDIDLE;
        RDDATA:
            if (RREADY & RVALID)
                rnext = RDIDLE;
            else
                rnext = RDDATA;
        default:
            rnext = RDIDLE;
    endcase
end

// rdata
always @(posedge ACLK) begin
    if (ACLK_EN) begin
        if (ar_hs) begin
            rdata <= 1'b0;
            case (raddr)
                ADDR_BIAS_DATA_0: begin
                    rdata <= int_bias[31:0];
                end
                ADDR_BIAS_CTRL: begin
                    rdata[0] <= int_bias_ap_vld;
                end
                ADDR_W1_DATA_0: begin
                    rdata <= int_w1[31:0];
                end
                ADDR_W1_CTRL: begin
                    rdata[0] <= int_w1_ap_vld;
                end
                ADDR_W2_DATA_0: begin
                    rdata <= int_w2[31:0];
                end
                ADDR_W2_CTRL: begin
                    rdata[0] <= int_w2_ap_vld;
                end
                ADDR_W3_DATA_0: begin
                    rdata <= int_w3[31:0];
                end
                ADDR_W3_CTRL: begin
                    rdata[0] <= int_w3_ap_vld;
                end
                ADDR_W4_DATA_0: begin
                    rdata <= int_w4[31:0];
                end
                ADDR_W4_CTRL: begin
                    rdata[0] <= int_w4_ap_vld;
                end
                ADDR_W5_DATA_0: begin
                    rdata <= int_w5[31:0];
                end
                ADDR_W5_CTRL: begin
                    rdata[0] <= int_w5_ap_vld;
                end
            endcase
        end
    end
end


//------------------------Register logic-----------------
// int_bias
always @(posedge ACLK) begin
    if (ARESET)
        int_bias <= 0;
    else if (ACLK_EN) begin
        if (bias_ap_vld)
            int_bias <= bias;
    end
end

// int_bias_ap_vld
always @(posedge ACLK) begin
    if (ARESET)
        int_bias_ap_vld <= 1'b0;
    else if (ACLK_EN) begin
        if (bias_ap_vld)
            int_bias_ap_vld <= 1'b1;
        else if (ar_hs && raddr == ADDR_BIAS_CTRL)
            int_bias_ap_vld <= 1'b0; // clear on read
    end
end

// int_w1
always @(posedge ACLK) begin
    if (ARESET)
        int_w1 <= 0;
    else if (ACLK_EN) begin
        if (w1_ap_vld)
            int_w1 <= w1;
    end
end

// int_w1_ap_vld
always @(posedge ACLK) begin
    if (ARESET)
        int_w1_ap_vld <= 1'b0;
    else if (ACLK_EN) begin
        if (w1_ap_vld)
            int_w1_ap_vld <= 1'b1;
        else if (ar_hs && raddr == ADDR_W1_CTRL)
            int_w1_ap_vld <= 1'b0; // clear on read
    end
end

// int_w2
always @(posedge ACLK) begin
    if (ARESET)
        int_w2 <= 0;
    else if (ACLK_EN) begin
        if (w2_ap_vld)
            int_w2 <= w2;
    end
end

// int_w2_ap_vld
always @(posedge ACLK) begin
    if (ARESET)
        int_w2_ap_vld <= 1'b0;
    else if (ACLK_EN) begin
        if (w2_ap_vld)
            int_w2_ap_vld <= 1'b1;
        else if (ar_hs && raddr == ADDR_W2_CTRL)
            int_w2_ap_vld <= 1'b0; // clear on read
    end
end

// int_w3
always @(posedge ACLK) begin
    if (ARESET)
        int_w3 <= 0;
    else if (ACLK_EN) begin
        if (w3_ap_vld)
            int_w3 <= w3;
    end
end

// int_w3_ap_vld
always @(posedge ACLK) begin
    if (ARESET)
        int_w3_ap_vld <= 1'b0;
    else if (ACLK_EN) begin
        if (w3_ap_vld)
            int_w3_ap_vld <= 1'b1;
        else if (ar_hs && raddr == ADDR_W3_CTRL)
            int_w3_ap_vld <= 1'b0; // clear on read
    end
end

// int_w4
always @(posedge ACLK) begin
    if (ARESET)
        int_w4 <= 0;
    else if (ACLK_EN) begin
        if (w4_ap_vld)
            int_w4 <= w4;
    end
end

// int_w4_ap_vld
always @(posedge ACLK) begin
    if (ARESET)
        int_w4_ap_vld <= 1'b0;
    else if (ACLK_EN) begin
        if (w4_ap_vld)
            int_w4_ap_vld <= 1'b1;
        else if (ar_hs && raddr == ADDR_W4_CTRL)
            int_w4_ap_vld <= 1'b0; // clear on read
    end
end

// int_w5
always @(posedge ACLK) begin
    if (ARESET)
        int_w5 <= 0;
    else if (ACLK_EN) begin
        if (w5_ap_vld)
            int_w5 <= w5;
    end
end

// int_w5_ap_vld
always @(posedge ACLK) begin
    if (ARESET)
        int_w5_ap_vld <= 1'b0;
    else if (ACLK_EN) begin
        if (w5_ap_vld)
            int_w5_ap_vld <= 1'b1;
        else if (ar_hs && raddr == ADDR_W5_CTRL)
            int_w5_ap_vld <= 1'b0; // clear on read
    end
end


//------------------------Memory logic-------------------

endmodule
