// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.2
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

#ifndef XBACKWARD_LITE_H
#define XBACKWARD_LITE_H

#ifdef __cplusplus
extern "C" {
#endif

/***************************** Include Files *********************************/
#ifndef __linux__
#include "xil_types.h"
#include "xil_assert.h"
#include "xstatus.h"
#include "xil_io.h"
#else
#include <stdint.h>
#include <assert.h>
#include <dirent.h>
#include <fcntl.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/mman.h>
#include <unistd.h>
#include <stddef.h>
#endif
#include "xbackward_lite_hw.h"

/**************************** Type Definitions ******************************/
#ifdef __linux__
typedef uint8_t u8;
typedef uint16_t u16;
typedef uint32_t u32;
#else
typedef struct {
    u16 DeviceId;
    u32 Axilites_BaseAddress;
} XBackward_lite_Config;
#endif

typedef struct {
    u32 Axilites_BaseAddress;
    u32 IsReady;
} XBackward_lite;

/***************** Macros (Inline Functions) Definitions *********************/
#ifndef __linux__
#define XBackward_lite_WriteReg(BaseAddress, RegOffset, Data) \
    Xil_Out32((BaseAddress) + (RegOffset), (u32)(Data))
#define XBackward_lite_ReadReg(BaseAddress, RegOffset) \
    Xil_In32((BaseAddress) + (RegOffset))
#else
#define XBackward_lite_WriteReg(BaseAddress, RegOffset, Data) \
    *(volatile u32*)((BaseAddress) + (RegOffset)) = (u32)(Data)
#define XBackward_lite_ReadReg(BaseAddress, RegOffset) \
    *(volatile u32*)((BaseAddress) + (RegOffset))

#define Xil_AssertVoid(expr)    assert(expr)
#define Xil_AssertNonvoid(expr) assert(expr)

#define XST_SUCCESS             0
#define XST_DEVICE_NOT_FOUND    2
#define XST_OPEN_DEVICE_FAILED  3
#define XIL_COMPONENT_IS_READY  1
#endif

/************************** Function Prototypes *****************************/
#ifndef __linux__
int XBackward_lite_Initialize(XBackward_lite *InstancePtr, u16 DeviceId);
XBackward_lite_Config* XBackward_lite_LookupConfig(u16 DeviceId);
int XBackward_lite_CfgInitialize(XBackward_lite *InstancePtr, XBackward_lite_Config *ConfigPtr);
#else
int XBackward_lite_Initialize(XBackward_lite *InstancePtr, const char* InstanceName);
int XBackward_lite_Release(XBackward_lite *InstancePtr);
#endif


u32 XBackward_lite_Get_bias(XBackward_lite *InstancePtr);
u32 XBackward_lite_Get_bias_vld(XBackward_lite *InstancePtr);
u32 XBackward_lite_Get_w1(XBackward_lite *InstancePtr);
u32 XBackward_lite_Get_w1_vld(XBackward_lite *InstancePtr);
u32 XBackward_lite_Get_w2(XBackward_lite *InstancePtr);
u32 XBackward_lite_Get_w2_vld(XBackward_lite *InstancePtr);
u32 XBackward_lite_Get_w3(XBackward_lite *InstancePtr);
u32 XBackward_lite_Get_w3_vld(XBackward_lite *InstancePtr);
u32 XBackward_lite_Get_w4(XBackward_lite *InstancePtr);
u32 XBackward_lite_Get_w4_vld(XBackward_lite *InstancePtr);
u32 XBackward_lite_Get_w5(XBackward_lite *InstancePtr);
u32 XBackward_lite_Get_w5_vld(XBackward_lite *InstancePtr);

#ifdef __cplusplus
}
#endif

#endif
