# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/ECTE433_LabFiles/compute_weight/compute_weight.srcs/sources_1/bd/compute_weight/ip/compute_weight_xbar_0/compute_weight_xbar_0.xci
# IP: The module: 'compute_weight_xbar_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/ECTE433_LabFiles/compute_weight/compute_weight.srcs/sources_1/bd/compute_weight/ip/compute_weight_xbar_0/compute_weight_xbar_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'compute_weight_xbar_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: C:/ECTE433_LabFiles/compute_weight/compute_weight.srcs/sources_1/bd/compute_weight/ip/compute_weight_xbar_0/compute_weight_xbar_0.xci
# IP: The module: 'compute_weight_xbar_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/ECTE433_LabFiles/compute_weight/compute_weight.srcs/sources_1/bd/compute_weight/ip/compute_weight_xbar_0/compute_weight_xbar_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'compute_weight_xbar_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
