// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.2
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

#ifndef __linux__

#include "xstatus.h"
#include "xparameters.h"
#include "xbackward_lite.h"

extern XBackward_lite_Config XBackward_lite_ConfigTable[];

XBackward_lite_Config *XBackward_lite_LookupConfig(u16 DeviceId) {
	XBackward_lite_Config *ConfigPtr = NULL;

	int Index;

	for (Index = 0; Index < XPAR_XBACKWARD_LITE_NUM_INSTANCES; Index++) {
		if (XBackward_lite_ConfigTable[Index].DeviceId == DeviceId) {
			ConfigPtr = &XBackward_lite_ConfigTable[Index];
			break;
		}
	}

	return ConfigPtr;
}

int XBackward_lite_Initialize(XBackward_lite *InstancePtr, u16 DeviceId) {
	XBackward_lite_Config *ConfigPtr;

	Xil_AssertNonvoid(InstancePtr != NULL);

	ConfigPtr = XBackward_lite_LookupConfig(DeviceId);
	if (ConfigPtr == NULL) {
		InstancePtr->IsReady = 0;
		return (XST_DEVICE_NOT_FOUND);
	}

	return XBackward_lite_CfgInitialize(InstancePtr, ConfigPtr);
}

#endif

