# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/sampleRNN_GRU/sampleRNN_GRU.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sampleRNN_GRU || ORIG_REF_NAME==sampleRNN_GRU} -quiet] -quiet

# IP: bd/sampleRNN_GRU/ip/sampleRNN_GRU_processing_system7_0_0/sampleRNN_GRU_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sampleRNN_GRU_processing_system7_0_0 || ORIG_REF_NAME==sampleRNN_GRU_processing_system7_0_0} -quiet] -quiet

# IP: bd/sampleRNN_GRU/ip/sampleRNN_GRU_axi_dma_0_0/sampleRNN_GRU_axi_dma_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sampleRNN_GRU_axi_dma_0_0 || ORIG_REF_NAME==sampleRNN_GRU_axi_dma_0_0} -quiet] -quiet

# IP: bd/sampleRNN_GRU/ip/sampleRNN_GRU_rst_ps7_0_100M_0/sampleRNN_GRU_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sampleRNN_GRU_rst_ps7_0_100M_0 || ORIG_REF_NAME==sampleRNN_GRU_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/sampleRNN_GRU/ip/sampleRNN_GRU_sampleRNN_GRU_0_0/sampleRNN_GRU_sampleRNN_GRU_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sampleRNN_GRU_sampleRNN_GRU_0_0 || ORIG_REF_NAME==sampleRNN_GRU_sampleRNN_GRU_0_0} -quiet] -quiet

# IP: bd/sampleRNN_GRU/ip/sampleRNN_GRU_axi_smc_1/sampleRNN_GRU_axi_smc_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sampleRNN_GRU_axi_smc_1 || ORIG_REF_NAME==sampleRNN_GRU_axi_smc_1} -quiet] -quiet

# IP: bd/sampleRNN_GRU/ip/sampleRNN_GRU_ps7_0_axi_periph_1/sampleRNN_GRU_ps7_0_axi_periph_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sampleRNN_GRU_ps7_0_axi_periph_1 || ORIG_REF_NAME==sampleRNN_GRU_ps7_0_axi_periph_1} -quiet] -quiet

# IP: bd/sampleRNN_GRU/ip/sampleRNN_GRU_auto_pc_0/sampleRNN_GRU_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==sampleRNN_GRU_auto_pc_0 || ORIG_REF_NAME==sampleRNN_GRU_auto_pc_0} -quiet] -quiet

# XDC: bd/sampleRNN_GRU/sampleRNN_GRU_ooc.xdc
