# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/ECTE433_LabFiles/backward_lite_features/backward_lite_features.srcs/sources_1/bd/custom_backward/ip/custom_backward_xbar_0/custom_backward_xbar_0.xci
# IP: The module: 'custom_backward_xbar_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/ECTE433_LabFiles/backward_lite_features/backward_lite_features.srcs/sources_1/bd/custom_backward/ip/custom_backward_xbar_0/custom_backward_xbar_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'custom_backward_xbar_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: C:/ECTE433_LabFiles/backward_lite_features/backward_lite_features.srcs/sources_1/bd/custom_backward/ip/custom_backward_xbar_0/custom_backward_xbar_0.xci
# IP: The module: 'custom_backward_xbar_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/ECTE433_LabFiles/backward_lite_features/backward_lite_features.srcs/sources_1/bd/custom_backward/ip/custom_backward_xbar_0/custom_backward_xbar_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'custom_backward_xbar_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
