# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/ECTE433_LabFiles/sampleRNN_GRU/sampleRNN_GRU.srcs/sources_1/bd/sampleRNN_GRU/ip/sampleRNN_GRU_processing_system7_0_0/sampleRNN_GRU_processing_system7_0_0.xci
# IP: The module: 'sampleRNN_GRU_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/ECTE433_LabFiles/sampleRNN_GRU/sampleRNN_GRU.srcs/sources_1/bd/sampleRNN_GRU/ip/sampleRNN_GRU_processing_system7_0_0/sampleRNN_GRU_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'sampleRNN_GRU_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: C:/ECTE433_LabFiles/sampleRNN_GRU/sampleRNN_GRU.srcs/sources_1/bd/sampleRNN_GRU/ip/sampleRNN_GRU_processing_system7_0_0/sampleRNN_GRU_processing_system7_0_0.xci
# IP: The module: 'sampleRNN_GRU_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/ECTE433_LabFiles/sampleRNN_GRU/sampleRNN_GRU.srcs/sources_1/bd/sampleRNN_GRU/ip/sampleRNN_GRU_processing_system7_0_0/sampleRNN_GRU_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'sampleRNN_GRU_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
