# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/compute_weight/compute_weight.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==compute_weight || ORIG_REF_NAME==compute_weight} -quiet] -quiet

# IP: bd/compute_weight/ip/compute_weight_processing_system7_0_0/compute_weight_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==compute_weight_processing_system7_0_0 || ORIG_REF_NAME==compute_weight_processing_system7_0_0} -quiet] -quiet

# IP: bd/compute_weight/ip/compute_weight_axi_smc_0/compute_weight_axi_smc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==compute_weight_axi_smc_0 || ORIG_REF_NAME==compute_weight_axi_smc_0} -quiet] -quiet

# IP: bd/compute_weight/ip/compute_weight_rst_ps7_0_100M_0/compute_weight_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==compute_weight_rst_ps7_0_100M_0 || ORIG_REF_NAME==compute_weight_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/compute_weight/ip/compute_weight_ps7_0_axi_periph_0/compute_weight_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==compute_weight_ps7_0_axi_periph_0 || ORIG_REF_NAME==compute_weight_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/compute_weight/ip/compute_weight_axi_dma_1_0/compute_weight_axi_dma_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==compute_weight_axi_dma_1_0 || ORIG_REF_NAME==compute_weight_axi_dma_1_0} -quiet] -quiet

# IP: bd/compute_weight/ip/compute_weight_compute_weight_2_0_0/compute_weight_compute_weight_2_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==compute_weight_compute_weight_2_0_0 || ORIG_REF_NAME==compute_weight_compute_weight_2_0_0} -quiet] -quiet

# IP: bd/compute_weight/ip/compute_weight_xbar_0/compute_weight_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==compute_weight_xbar_0 || ORIG_REF_NAME==compute_weight_xbar_0} -quiet] -quiet

# IP: bd/compute_weight/ip/compute_weight_auto_pc_0/compute_weight_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==compute_weight_auto_pc_0 || ORIG_REF_NAME==compute_weight_auto_pc_0} -quiet] -quiet

# XDC: bd/compute_weight/compute_weight_ooc.xdc
