# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7z020clg400-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/ECTE433_LabFiles/backward_lite_features/backward_lite_features.cache/wt [current_project]
set_property parent.project_path C:/ECTE433_LabFiles/backward_lite_features/backward_lite_features.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_FIFO XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part www.digilentinc.com:pynq-z1:part0:1.0 [current_project]
set_property ip_repo_paths {
  c:/Users/manoh/Desktop/ECTE451/custom_backward/custom_backward
  c:/Users/manoh/Desktop/ECTE451/equation_matrix
  c:/Users/manoh/Desktop/ECTE451/backward_lite
  c:/Users/manoh/Desktop/ECTE451/custom_backward_single_dma_optim
  c:/Users/manoh/Desktop/ECTE451/custom_backward_single_dma
  c:/Users/manoh/Desktop/ECTE451/axi_stream_new_style
  c:/Users/manoh/Desktop/ECTE451/custom_backward_optim/custom_backward_optim
} [current_project]
set_property ip_output_repo c:/ECTE433_LabFiles/backward_lite_features/backward_lite_features.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib C:/ECTE433_LabFiles/backward_lite_features/backward_lite_features.srcs/sources_1/bd/custom_backward/hdl/custom_backward_wrapper.vhd
add_files C:/ECTE433_LabFiles/backward_lite_features/backward_lite_features.srcs/sources_1/bd/custom_backward/custom_backward.bd
set_property used_in_implementation false [get_files -all c:/ECTE433_LabFiles/backward_lite_features/backward_lite_features.srcs/sources_1/bd/custom_backward/ip/custom_backward_processing_system7_0_0/custom_backward_processing_system7_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/ECTE433_LabFiles/backward_lite_features/backward_lite_features.srcs/sources_1/bd/custom_backward/ip/custom_backward_rst_ps7_0_100M_0/custom_backward_rst_ps7_0_100M_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/ECTE433_LabFiles/backward_lite_features/backward_lite_features.srcs/sources_1/bd/custom_backward/ip/custom_backward_rst_ps7_0_100M_0/custom_backward_rst_ps7_0_100M_0.xdc]
set_property used_in_implementation false [get_files -all c:/ECTE433_LabFiles/backward_lite_features/backward_lite_features.srcs/sources_1/bd/custom_backward/ip/custom_backward_rst_ps7_0_100M_0/custom_backward_rst_ps7_0_100M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/ECTE433_LabFiles/backward_lite_features/backward_lite_features.srcs/sources_1/bd/custom_backward/ip/custom_backward_axi_dma_0_0/custom_backward_axi_dma_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/ECTE433_LabFiles/backward_lite_features/backward_lite_features.srcs/sources_1/bd/custom_backward/ip/custom_backward_axi_dma_0_0/custom_backward_axi_dma_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/ECTE433_LabFiles/backward_lite_features/backward_lite_features.srcs/sources_1/bd/custom_backward/ip/custom_backward_axi_dma_0_0/custom_backward_axi_dma_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/ECTE433_LabFiles/backward_lite_features/backward_lite_features.srcs/sources_1/bd/custom_backward/ip/custom_backward_xbar_0/custom_backward_xbar_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/ECTE433_LabFiles/backward_lite_features/backward_lite_features.srcs/sources_1/bd/custom_backward/ip/custom_backward_xbar_1/custom_backward_xbar_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/ECTE433_LabFiles/backward_lite_features/backward_lite_features.srcs/sources_1/bd/custom_backward/ip/custom_backward_backward_lite_0_0/constraints/backward_lite_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/ECTE433_LabFiles/backward_lite_features/backward_lite_features.srcs/sources_1/bd/custom_backward/ip/custom_backward_equation_matrix_0_0/constraints/equation_matrix_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/ECTE433_LabFiles/backward_lite_features/backward_lite_features.srcs/sources_1/bd/custom_backward/ip/custom_backward_axi_dma_1_0/custom_backward_axi_dma_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/ECTE433_LabFiles/backward_lite_features/backward_lite_features.srcs/sources_1/bd/custom_backward/ip/custom_backward_axi_dma_1_0/custom_backward_axi_dma_1_0.xdc]
set_property used_in_implementation false [get_files -all c:/ECTE433_LabFiles/backward_lite_features/backward_lite_features.srcs/sources_1/bd/custom_backward/ip/custom_backward_axi_dma_1_0/custom_backward_axi_dma_1_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/ECTE433_LabFiles/backward_lite_features/backward_lite_features.srcs/sources_1/bd/custom_backward/ip/custom_backward_auto_pc_1/custom_backward_auto_pc_1_ooc.xdc]
set_property used_in_synthesis false [get_files -all c:/ECTE433_LabFiles/backward_lite_features/backward_lite_features.srcs/sources_1/bd/custom_backward/ip/custom_backward_auto_us_2/custom_backward_auto_us_2_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/ECTE433_LabFiles/backward_lite_features/backward_lite_features.srcs/sources_1/bd/custom_backward/ip/custom_backward_auto_us_2/custom_backward_auto_us_2_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/ECTE433_LabFiles/backward_lite_features/backward_lite_features.srcs/sources_1/bd/custom_backward/ip/custom_backward_auto_us_2/custom_backward_auto_us_2_ooc.xdc]
set_property used_in_synthesis false [get_files -all c:/ECTE433_LabFiles/backward_lite_features/backward_lite_features.srcs/sources_1/bd/custom_backward/ip/custom_backward_auto_us_1/custom_backward_auto_us_1_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/ECTE433_LabFiles/backward_lite_features/backward_lite_features.srcs/sources_1/bd/custom_backward/ip/custom_backward_auto_us_1/custom_backward_auto_us_1_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/ECTE433_LabFiles/backward_lite_features/backward_lite_features.srcs/sources_1/bd/custom_backward/ip/custom_backward_auto_us_1/custom_backward_auto_us_1_ooc.xdc]
set_property used_in_synthesis false [get_files -all c:/ECTE433_LabFiles/backward_lite_features/backward_lite_features.srcs/sources_1/bd/custom_backward/ip/custom_backward_auto_us_0/custom_backward_auto_us_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/ECTE433_LabFiles/backward_lite_features/backward_lite_features.srcs/sources_1/bd/custom_backward/ip/custom_backward_auto_us_0/custom_backward_auto_us_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/ECTE433_LabFiles/backward_lite_features/backward_lite_features.srcs/sources_1/bd/custom_backward/ip/custom_backward_auto_us_0/custom_backward_auto_us_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/ECTE433_LabFiles/backward_lite_features/backward_lite_features.srcs/sources_1/bd/custom_backward/ip/custom_backward_auto_pc_0/custom_backward_auto_pc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all C:/ECTE433_LabFiles/backward_lite_features/backward_lite_features.srcs/sources_1/bd/custom_backward/custom_backward_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 0
close [open __synthesis_is_running__ w]

synth_design -top custom_backward_wrapper -part xc7z020clg400-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef custom_backward_wrapper.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file custom_backward_wrapper_utilization_synth.rpt -pb custom_backward_wrapper_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
