# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/custom_backward/custom_backward.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==custom_backward || ORIG_REF_NAME==custom_backward} -quiet] -quiet

# IP: bd/custom_backward/ip/custom_backward_processing_system7_0_0/custom_backward_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==custom_backward_processing_system7_0_0 || ORIG_REF_NAME==custom_backward_processing_system7_0_0} -quiet] -quiet

# IP: bd/custom_backward/ip/custom_backward_ps7_0_axi_periph_0/custom_backward_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==custom_backward_ps7_0_axi_periph_0 || ORIG_REF_NAME==custom_backward_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/custom_backward/ip/custom_backward_rst_ps7_0_100M_0/custom_backward_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==custom_backward_rst_ps7_0_100M_0 || ORIG_REF_NAME==custom_backward_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/custom_backward/ip/custom_backward_axi_dma_0_0/custom_backward_axi_dma_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==custom_backward_axi_dma_0_0 || ORIG_REF_NAME==custom_backward_axi_dma_0_0} -quiet] -quiet

# IP: bd/custom_backward/ip/custom_backward_axi_interconnect_0_0/custom_backward_axi_interconnect_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==custom_backward_axi_interconnect_0_0 || ORIG_REF_NAME==custom_backward_axi_interconnect_0_0} -quiet] -quiet

# IP: bd/custom_backward/ip/custom_backward_xbar_0/custom_backward_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==custom_backward_xbar_0 || ORIG_REF_NAME==custom_backward_xbar_0} -quiet] -quiet

# IP: bd/custom_backward/ip/custom_backward_xbar_1/custom_backward_xbar_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==custom_backward_xbar_1 || ORIG_REF_NAME==custom_backward_xbar_1} -quiet] -quiet

# IP: bd/custom_backward/ip/custom_backward_backward_lite_0_0/custom_backward_backward_lite_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==custom_backward_backward_lite_0_0 || ORIG_REF_NAME==custom_backward_backward_lite_0_0} -quiet] -quiet

# IP: bd/custom_backward/ip/custom_backward_equation_matrix_0_0/custom_backward_equation_matrix_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==custom_backward_equation_matrix_0_0 || ORIG_REF_NAME==custom_backward_equation_matrix_0_0} -quiet] -quiet

# IP: bd/custom_backward/ip/custom_backward_axi_dma_1_0/custom_backward_axi_dma_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==custom_backward_axi_dma_1_0 || ORIG_REF_NAME==custom_backward_axi_dma_1_0} -quiet] -quiet

# IP: bd/custom_backward/ip/custom_backward_auto_pc_1/custom_backward_auto_pc_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==custom_backward_auto_pc_1 || ORIG_REF_NAME==custom_backward_auto_pc_1} -quiet] -quiet

# IP: bd/custom_backward/ip/custom_backward_auto_us_2/custom_backward_auto_us_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==custom_backward_auto_us_2 || ORIG_REF_NAME==custom_backward_auto_us_2} -quiet] -quiet

# IP: bd/custom_backward/ip/custom_backward_auto_us_1/custom_backward_auto_us_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==custom_backward_auto_us_1 || ORIG_REF_NAME==custom_backward_auto_us_1} -quiet] -quiet

# IP: bd/custom_backward/ip/custom_backward_auto_us_0/custom_backward_auto_us_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==custom_backward_auto_us_0 || ORIG_REF_NAME==custom_backward_auto_us_0} -quiet] -quiet

# IP: bd/custom_backward/ip/custom_backward_auto_pc_0/custom_backward_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==custom_backward_auto_pc_0 || ORIG_REF_NAME==custom_backward_auto_pc_0} -quiet] -quiet

# XDC: bd/custom_backward/custom_backward_ooc.xdc
